- name: Debugging some vars
  debug:
    var: my_ansible_command

- name: Deploy wiki.js
  command: "docker-compose -p wiki {{ item }}"
  register: my_output
  loop:
  - down
  - up -d
  - ps

- debug:
    msg: |
      ---
      my_output (with list filtered by not empty attribute 'stdout' and select only the values of 'stdout'):
      {{ my_output.results | selectattr('stdout', 'ne', '') | map(attribute='stdout') | list | to_nice_yaml }}
      ----
