- name: Debugging some vars
  debug:
    var: my_ansible_command
#    msg: "{{ my_ansible_command }}"
- name: Deploy wiki.js
  command: "docker-compose -p wiki {{ item }}"
  loop:
  - down
  - up -d
  - ps

